version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  auth-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=waste_management
      - DB_PORT=5432
      - JWT_SECRET=supersecret
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: waste_management
      POSTGRES_USER: wasteman
      POSTGRES_PASSWORD: secure_password

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"